# Generated by Django 6.0.3 on 2026-04-12 15:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_btn_label',
            field=models.CharField(blank=True, default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_btn_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_features',
            field=wagtail.fields.StreamField([('about_feature', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('text', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_img2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_img3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_main', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_btn_label',
            field=models.CharField(blank=True, default='More About Admission', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_btn_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_checklist',
            field=wagtail.fields.StreamField([('checklist', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.ListBlock', (0,), {'label': 'Left Column Items'}), 2: ('wagtail.blocks.ListBlock', (0,), {'label': 'Right Column Items'}), 3: ('wagtail.blocks.StructBlock', [[('items_column_1', 1), ('items_column_2', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='apply_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_explore_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_posts',
            field=wagtail.fields.StreamField([('post', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.DateBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('category', 1), ('date', 2), ('title', 3), ('author', 1), ('link_url', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_btn_label',
            field=models.CharField(blank=True, default='Lecturer at Faculty', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_btn_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chancellor_photo', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_name',
            field=models.CharField(blank=True, help_text='e.g. Prof. Dr. Simons Doe, Ph.D', max_length=150),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chancellor_sig', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_skills',
            field=wagtail.fields.StreamField([('skill_bar', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.IntegerBlock', (), {'max_value': 100, 'min_value': 0}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('percentage', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chancellor_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_bg', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_btn_label',
            field=models.CharField(blank=True, default='Join Community', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_btn_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='counter_stats',
            field=wagtail.fields.StreamField([('counter', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 157, 18,250, 48k', 'max_length': 20}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. +, k', 'max_length': 5, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 4: ('wagtail.blocks.StructBlock', [[('icon', 0), ('number', 1), ('suffix', 2), ('label', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events',
            field=wagtail.fields.StreamField([('event', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 15', 'max_length': 2}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Aug', 'max_length': 3}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.DateBlock', (), {}), 6: ('wagtail.blocks.TimeBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 0), ('day', 1), ('month', 2), ('title', 3), ('description', 4), ('location', 3), ('date', 5), ('time_from', 6), ('time_to', 6), ('link_url', 7)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_explore_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_img1', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_img2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_img3', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_items',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_cards',
            field=wagtail.fields.StreamField([('feature_card', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 50}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('text', 2), ('link_url', 3), ('link_label', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_section_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright_name',
            field=models.CharField(blank=True, default='Stadum', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright_year',
            field=models.CharField(blank=True, default='2025', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_logo_img', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge_text',
            field=models.CharField(blank=True, help_text="e.g. '1996 EST * 25 Years Quality Teaching'", max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_label',
            field=models.CharField(blank=True, default='Explore Programs', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_label',
            field=models.CharField(blank=True, default='Watch Video', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Hero Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_established_year',
            field=models.CharField(blank=True, help_text='e.g. 1996', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_main_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_small_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_small_img1', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_small_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_small_img2', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero Sub-label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero Headline'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_dark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_dark_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='marquee_items',
            field=wagtail.fields.StreamField([('item', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('text', 1), ('link_url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='program_cards',
            field=wagtail.fields.StreamField([('program', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Media, Science', 'max_length': 50}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 1, 'help_text': 'e.g. 4.8', 'max_digits': 3}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 04 Years', 'max_length': 50}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 0), ('tag', 1), ('title', 2), ('rating', 3), ('description', 4), ('language', 5), ('duration', 6), ('link_url', 7)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='programs_explore_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='programs_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='programs_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stories_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stories_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('photo', 0), ('name', 1), ('quote', 2), ('profile_url', 3)]], {})}),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
